# Generated by Django 3.2 on 2022-06-25 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wish_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='list',
        ),
        migrations.AddField(
            model_name='wish',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='Wish_App.User'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='date_gran',
            field=models.DateField(default='0000-00-00'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish', to='Wish_App.user'),
        ),
    ]
