# Generated by Django 3.2 on 2022-06-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wish_App', '0006_user_wish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='date_add',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='grand_date',
            field=models.DateField(auto_now=True),
        ),
    ]
